### PR TITLE
Qt6 / Pyside6

### PR DESCRIPTION
**Pull request by looooo**

### CODE REVIEW

**Comment by looooo** [comment]
unix qt6: conda solver issue
```
         raise ValueError(
2023-11-21T18:23:12.2157472Z     ValueError: Incompatible component merge:
2023-11-21T18:23:12.2157924Z       - '*mpich*'
2023-11-21T18:23:12.2158307Z       - 'mpi_mpich_*'
```

win qt6: solver not able to resolve dependencies.

@conda-forge/core can you have a look at this? Are these known issues?

**Comment by looooo** [comment]
@conda-forge/core any ideas how to update visual-studio? 

```
fatal error C1189: #error:  "Qt requires at least Visual Studio 2019 version 16.7 (VC++ version 14.27). Please upgrade."
```

**Comment by hmaarrfk** [comment]
maybe this can help:
https://github.com/marketplace/actions/setup-msbuild

**Comment by oursland** [comment]
> @conda-forge/core any ideas how to update visual-studio?
> 
> ```
> fatal error C1189: #error:  "Qt requires at least Visual Studio 2019 version 16.7 (VC++ version 14.27). Please upgrade."
> ```

The issue is that the `conda` packages for newer compilers have not been installed.  See [here where it identifies that `vs2017_win-64` is installed](https://github.com/coin3d/pivy/actions/runs/6997569796/job/19034685826#step:6:119).  The metapackage `compilers` will bring in `vs2019`, the current standard for `conda` builds on Windows.

Eventually the `compilers` package is to be upgraded to `vs2022` and support both `x86-64` and `arm64` builds.

**Comment by oursland** [comment]
~Looks like another issue now, with the command interpreter failing due to some [input line too long](https://github.com/coin3d/pivy/actions/runs/7050032278/job/19189819293?pr=108#step:6:318).~

~To get conda environments to work on Windows runners I have had to specify the shell as `cmd /C CALL {0}` as shown [here](https://github.com/oursland/FreeCAD/blob/ci-update/.github/workflows/sub_buildWindowsConda.yml#L116C9-L116C9).~

I forked it and got it working by removing `{{ compiler("cxx") }}` macro and replacing it with `compilers` package for all platforms: https://github.com/oursland/pivy/commit/f052a51dfbca0bb06267fdf6a89b5e7014306c10

**Pull request merged**
